services:
  # API
  platform-api:
    build:
      context: .docker
      dockerfile: Dockerfile
    image: platform-api:latest
    container_name: platform-api
    restart: unless-stopped
    tty: true
    ports:
      - 8080:8080
      - '${REVERB_PORT:-6001}:6001'
    volumes:
      - ./:/var/www/html
      - ./.docker/php.ini:/usr/local/etc/php/conf.d/99-php.ini
      - ./.docker/xdebug.ini:/usr/local/etc/php/conf.d/20-xdebug.ini
      - ./.docker/fpm-pool.conf:/usr/local/etc/php-fpm.conf
      - ~/.ssh:/home/laravel/.ssh
    cap_add:
      - SYS_ADMIN
    environment:
      - XDEBUG_SESSION=${XDEBUG_SESSION:-0}
      - XDEBUG_CONFIG=${XDEBUG_CONFIG:-client_host=host.docker.internal}
    depends_on:
      - db
      - redis
      - mail
    networks:
      - default-network

  # Nginx
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - platform-api
    networks:
      - default-network

  # Database
  db:
    image: postgres:17
    container_name: db
    restart: unless-stopped
    ports:
      - ${DB_PORT:-5432}:5432
    environment:
      - POSTGRES_DB=${DB_DATABASE:-laravel}
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD:-P@ssw0rd}
      - DB_USERNAME=${DB_USERNAME:-laravel}
      - DB_PASSWORD=${DB_PASSWORD:-P@ssw0rd}
      - POSTGRES_MULTIPLE_DATABASES=${DB_DATABASE:-laravel},laravel_testing
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./.docker/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - default-network

  # Redis
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - ${REDIS_PORT:-6379}:6379
    volumes:
      - redis:/data
    networks:
      - default-network

  # Mail
  mail:
    image: axllent/mailpit:latest
    container_name: mail
    restart: unless-stopped
    ports:
      - ${MAIL_PORT:-1025}:1025
      - 8025:8025
    networks:
      - default-network

# Networks
networks:
  default-network:

# Volumes
volumes:
  postgres:
    driver: local
  redis:
    driver: local
